_target_: src.models.cora_module.CoraLitModule
lr: 2e-5

model:
  _target_: src.models.components.bert_token_classifier_double.BertTokenClassifierDouble
  model_checkpoint: ${paths.root_dir}/pretrained/scibert-synthetic-uncased-full-100k"
  output_size: 13
  cache_dir: ${paths.root_dir}/.cache/
