_target_: src.models.synthetic_module.SyntheticLitModule
lr: 2e-5

model:
  _target_: src.models.components.bert_token_classifier.BertTokenClassifier
  model_checkpoint: "allenai/scibert_scivocab_uncased"
  output_size: 19
  cache_dir: ${paths.root_dir}/.cache/
