_target_: SciAssist.models.cora_module.CoraLitModule
lr: 2e-5
data_utils:
  _target_: SciAssist.utils.data_utils.DataUtilsForTokenClassification

model:
  _target_: SciAssist.models.components.bert_token_classifier.BertForTokenClassifier
  model_checkpoint: "allenai/scibert_scivocab_uncased"
  output_size: 13
  cache_dir: ${paths.root_dir}/.cache/
  save_name: ${model_name}
  model_dir: ${paths.model_dir}