_target_: SciAssist.models.mup_bart_module.MupBartLitModule
lr: 5e-4
data_utils: ${datamodule.data_utils}

model:
  _target_: SciAssist.models.components.flant5_summarization.FlanT5ForSummarization
  model_checkpoint: "google/flan-t5-large"
  cache_dir: ${paths.root_dir}/.cache/
  save_name: ${model_name}
  model_dir: ${paths.model_dir}