# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: dataset_extraction.yaml # choose the datamodule for evaluation
  - model: dataset_extraction.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml
  - paths: default.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null


# passing checkpoint path is necessary
ckpt_path: /home/linxiao/SciAssist-refactor-0202/src/models/roberta_ner/2023-02-08_18-11-31/checkpoints/epoch_001.ckpt

name: "default"
model_name: ${ckpt_path}